### ISSUE TITLE
Object.values

### ISSUE THREAD

**Issue by cjessett** [fpl1976/bapi-p3-the-scoop#2]
(Simplify) [Here](https://github.com/fpl1976/bapi-p3-the-scoop/blob/98c5aa4670bb0ce71532dc4217378b0e8bee1de6/project-3-the-scoop/server.js#L101-L102) instead of grabbing the keys and then mapping to get the `articles`(or values) just use `Object.values`.

**Comment by fpl1976** [comment]
This code is not mine, was provided at the start zip
